name: build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # 每天 UTC 时间 00:00 运行

jobs:
  build-windows-amd64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add wasm32-wasi
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - run: cargo build --release
      - run: ren target\release\Zed.exe Zed-windows-amd64.exe
      - uses: actions/upload-artifact@v4
        with:
          name: Zed-windows-amd64
          path: target\release\Zed-windows-amd64.exe
          
  build-windows-x86:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add wasm32-wasi
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86
      - run: cargo build --release
      - run: ren target\release\Zed.exe Zed-windows-x86.exe
      - uses: actions/upload-artifact@v4
        with:
          name: zed-windows-x86
          path: target\release\Zed-windows-x86.exe

  build-windows-arm64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add wasm32-wasi
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_arm64
      - run: cargo build --release
      - run: ren target\release\Zed.exe Zed-windows-arm64.exe
      - uses: actions/upload-artifact@v4
        with:
          name: Zed-windows-arm64
          path: target\release\Zed-windows-arm64.exe

  upload-to-release:
    runs-on: ubuntu-latest
    needs: [build-windows-amd64,build-windows-x86,build-windows-arm64]
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: Zed-*
          merge-multiple: true
      - uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: 自动构建
          tag_name: auto
          body: 自动构建
          generate_release_notes: true
          files: |
            Zed-windows-amd64.exe
            Zed-windows-x86.exe
            Zed-windows-arm64.exe
